### ISSUE TITLE
folkfriend.exe behave differently than Web version ?

### ISSUE THREAD

**Issue by lerbourl** [TomWyllie/folkfriend#41]
Hi Tom,
I've compiled FF myself using cargo and get folkfriend.exe on windows. EDIT : was tested on linux ubuntu too.
Now I want to transcribe and query a .wav audio file.

For the same wav file, it seems to work online at https://folkfriend.app but not with my compiled folkfriend.exe.

Am I missing something ? Do you apply a filter to the .wav audio file before using the rust worker in the webapp ?

folkfriend.app output is great (recognizing mountain dew) :

K:Emin
Eg2ed BA2FA |B2EBG BEB3G |BADF AaBE |_BaEg2 ed=Bg'2 |
FAB2e gfde |dB2eg f2dD2B2 |egfe dc'AG |FD2AD aBeg |
fded B2egf |d2D^cd fafg |fedB dABE2 |B4BGB EBb'G |
BADF BEBG |BEg2e dBAD |FABE B |

But folkfriend.exe output is nonsens :

K:Emin
G3ED2B,2 b'2A,2g'A, |b'4b'_b'B, b'2B,c'b'2 |b'2_b'g'=b' B,g'3gb' |_b'g'4g'G ^G=GE2B, |
g'3_b'g'4B,2 EG2F2D |E2D2g'f' B,2E2GF |DA^g=g ^g=g'2E2G |g'Fg'_b g'^g'=g'=b' |
g'f'g'g _b'2=b'2g'2b' |g'2f'2_b'g'2 Gg'2b'E |^cg'f'g' EGFb' |Df'gb g'3FA,2F |
G2FEc g'^c'_b'^d' |_b'c'A,g' f'cg'2b' |^d'e'=f^f' B,g'_b'=b'2 |_b'2=b'g'b' f'_b'=b'2g' |
_b'=b'3g'_b'2 =b'g'4cg'2 |GE2_b'3a gg'3A,f'2 |g'b'2g' |

**Comment by lerbourl** [comment]
[irish.wav.zip](https://github.com/TomWyllie/folkfriend/files/11546406/irish.wav.zip)

This wav file was used

**Comment by TomWyllie** [comment]
Hi there - I can confirm that this issue arises from using a stereo wav file rather than a mono wav file. You can preprocess the audio file with 

`ffmpeg -i irish.wav -ac 1 irish_mono.wav`

To mix down to one audio channel. The command line version of folkfriend will then work as expected on the mono audio file. The browser version of FolkFriend uses WebAudio to do this step automatically, but the wav file being read in through rust does not have access to WebAudio to do this step. It reads the raw samples and treats the stereo samples as mono samples which at best lowers everything by an octave and at worst causes garbage input / garbage output.

In future the FolkFriend command line version should either fail with an error for stereo files, or automatically mix them down to mono - for now please just ensure you are only using 48 kHz mono .wav files as input - I recommend `ffmpeg` to do this step 😊
